fix: fix: Link takes to the Github page even if click out side the button
OpenSource-Journey/Your-Github-Contributions pull request #31
Opened 2023-03-04 10:41 UTC by Hat52

Closes #30  
https://www.loom.com/share/7e31f2d3ed6449deb30513271b547969

2023-03-04 14:01 UTC, Sachin-chaurasiya commented
Hey @Hat52 , thanks for the PR, there is a merge conflict in your please resolve it.

2023-03-04 14:15 UTC, Sachin-chaurasiya requested changes
Left a few comments, thanks

2023-03-04 14:15 UTC, Sachin-chaurasiya commented on src/pages/HomePage/HomePage.tsx
> +		style={{width:'max-content'}}
@Hat52 , Chakra UI supports CSS in JSX, so you don't have to use the style object to give the styling to the element.

For more you can refer this https://chakra-ui.com/getting-started
```suggestion
		width:'max-content'
                 margin='auto'
```

2023-03-04 14:15 UTC, Sachin-chaurasiya commented on src/pages/HomePage/HomePage.tsx
> +	<Flex justifyContent="center">
We don't need flex, `margin: auto` will work here.

2023-03-08 08:30 UTC, Sachin-chaurasiya commented
@Hat52 , I think you have mixed up the changes of issues #27 and #30.

This PR should only include the changes for issue #30

2023-03-08 08:58 UTC, Hat52 commented
> @Hat52 , I think you have mixed up the changes of issues #27 and #30.
> 
> This PR should only include the changes for issue #30 

I have already created the PR for #27. the extra changes are of that issue. If you review that PR and merge it then we are good to go.

2023-03-08 09:38 UTC, Sachin-chaurasiya commented
> > @Hat52 , I think you have mixed up the changes of issues #27 and #30.
> 
> > 
> 
> > This PR should only include the changes for issue #30 
> 
> 
> 
> I have already created the PR for #27. the extra changes are of that issue. If you review that PR and merge it then we are good to go.

I saw your another PR, my point was this PR should only have the changes for issue #30 only.

2023-03-08 13:33 UTC, Hat52 commented
> our

Yes, I got your point. The issue is I mistakenly made changes of the first PR in the main branch and after changes I switched to new branch.

Now I don't know how I can revert the changes from main branch

2023-03-08 13:46 UTC, Sachin-chaurasiya commented
> > our
> 
> Yes, I got your point. The issue is I mistakenly made changes of the first PR in the main branch and after changes I switched to new branch.
> 
> Now I don't know how I can revert the changes from main branch

Hello @Hat52 , Here are the steps that you can follow.

- Switch to this PR branch `git checkout link-redirect`
- Remove the Image related changes and only keep the `Star on GitHub` button changes.
- Push the change to the `link-redirect` branch.

2023-03-08 15:18 UTC, Hat52 commented
@Sachin-chaurasiya Done

> > > our
> > 
> > 
> > Yes, I got your point. The issue is I mistakenly made changes of the first PR in the main branch and after changes I switched to new branch.
> > Now I don't know how I can revert the changes from main branch
> 
> Hello @Hat52 , Here are the steps that you can follow.
> 
> * Switch to this PR branch `git checkout link-redirect`
> * Remove the Image related changes and only keep the `Star on GitHub` button changes.
> * Push the change to the `link-redirect` branch.

@Sachin-chaurasiya Done

2023-03-08 15:23 UTC, Sachin-chaurasiya approved these changes
Great work @Hat52  🙌🏻,
Thanks for the contributions ✨

2023-03-08 15:24 UTC, merged