Btn color consistency
OpenSource-Journey/Your-Github-Contributions pull request #44
Opened 2023-03-16 18:21 UTC by mayukh551

## Pull Request Checklist

@Sachin-chaurasiya 

Before submitting a pull request, please make sure that your changes meet the following criteria:

- [ ] Ensure that your code adheres to our coding conventions and is properly formatted.
- [ ] Test your changes extensively to ensure that they do not introduce any new bugs.
- [ ] Confirm that you agree to the code of conduct.

## Related Issues

If this pull request is related to any issues, please list them here.
#43 

## Screenshots

If your changes include any visual elements, please provide screenshots or other visual aids to help reviewers understand your changes.

## Additional Notes

If there is anything else you would like to note about your changes or the review process, please add it here.

2023-03-16 18:26 UTC, Sachin-chaurasiya commented
@mayukh551 , Thanks for the PR, a couple of things.
- Do not push the package-lock.json file ( for the development purpose we recommend using the `yarn`)
- Do not upgrade or uninstall the packages ( if not needed )
- Your PR should be scoped to the related issue.

2023-03-16 18:28 UTC, Sachin-chaurasiya requested changes
Left a few comments, thanks

2023-03-16 18:28 UTC, Sachin-chaurasiya commented on README.md
> -
@mayukh551 , Can you remove this change?

2023-03-16 18:28 UTC, Sachin-chaurasiya commented on package-lock.json
@mayukh551 , Please do not push this file.

2023-03-16 18:28 UTC, Sachin-chaurasiya commented on package.json
@mayukh551 , Please revert these file changes.

2023-03-16 18:28 UTC, Sachin-chaurasiya commented on yarn.lock
@mayukh551 , Please revert these file changes.

2023-03-17 04:45 UTC, mayukh551 commented
@Sachin-chaurasiya I understand where I made the mistake. Since, it's a small change, I am going to create a new PR by closing this one.

2023-03-17 04:45 UTC, closed without merging