Fix: User profile copy button is not working
OpenSource-Journey/Your-Github-Contributions pull request #55
Opened 2023-03-19 17:51 UTC by zt4ff

## Pull Request Checklist

Before submitting a pull request, please make sure that your changes meet the following criteria:

- [X] Ensure that your code adheres to our coding conventions and is properly formatted.
- [X] Test your changes extensively to ensure that they do not introduce any new bugs.
- [X] Confirm that you agree to the code of conduct.

## Related Issues
#53 
If this pull request is related to any issues, please list them here.

## Screenshots

If your changes include any visual elements, please provide screenshots or other visual aids to help reviewers understand your changes.

## Additional Notes

If there is anything else you would like to note about your changes or the review process, please add it here.

2023-03-19 17:52 UTC, zt4ff commented
Hi maintainer! It's my first time contributing to your repo. I look forward to your response and feedback.

2023-03-19 19:57 UTC, Sachin-chaurasiya commented
> Hi maintainer! It's my first time contributing to your repo. I look forward to your response and feedback.


Hello @zt4ff , Welcome to the @OpenSource-Journey community.

Thanks for the PR.

A few things,

- Read the contributions guidelines 
- If you want to work on any issue first ask maintainers to assign it to you, once issue is assigned to you, can start working on it and raise a PR.

2023-03-19 19:59 UTC, Sachin-chaurasiya commented
@zt4ff, comment on this #53 issue and I will assign it to you.

2023-03-20 04:34 UTC, ShaileshParmar11 requested changes

2023-03-20 04:34 UTC, ShaileshParmar11 commented on src/pages/UserPage/UserPage.tsx
>      const url = `${window.location.protocol}//${window.location.host}/${userName}`;
could you verify whether it is working or not? please also add a video of the changes in the description

2023-03-25 19:35 UTC, Sachin-chaurasiya commented
Hello @zt4ff , Let us know if you are facing any difficulties or have questions. Thanks

2023-04-01 08:09 UTC, Sachin-chaurasiya commented
Hello @zt4ff, Any progress on this PR?

2023-04-02 20:20 UTC, zt4ff commented
@Sachin-chaurasiya, sorry about the late response. I was away from my devices for a while now. I am back now and work on the comment you dropped ASAP

2023-04-03 05:27 UTC, Sachin-chaurasiya commented
> @Sachin-chaurasiya, sorry about the late response. I was away from my devices for a while now. I am back now and work on the comment you dropped ASAP

No worries @zt4ff , thanks.

2023-04-29 13:23 UTC, Sachin-chaurasiya commented
Hello @zt4ff , Any progress?

2023-04-29 13:30 UTC, merged

2023-04-29 13:37 UTC, Sachin-chaurasiya commented
@all-contributors please add @zt4ff  for Code